# TomEE MicroProfile JWT Starter Project

This incredibly small starter project is focused on the minimum project structure one would need in the real world to use MicroProfile JWT.

With MicroProfile JWT, the implementation provides all JWT verification libraries.
Our only job as a developer wishing to use MicroProfile JWT is to tell the implementation how to get the RSA public key of the JWT creator for verification purposes.

Under the `src/main` we have the following files that would be required to run MicroProfile JWT in production.

 - src/main/java/org/superbiz/Api.java
 - src/main/java/org/superbiz/Movie.java
 - src/main/java/org/superbiz/MovieService.java
 - src/main/resources/META-INF/microprofile-config.properties

One approach to setting up MicroProfile JWT is to embed the public key in the application itself as follows:

[source,properties]
----
#
# The public key of the authorization server (a.k.a. token creator)
#
mp.jwt.verify.publickey=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyzNurU19lqnYhx5QI72sIX1lh8cTehTmboC+DLG7UuaUHqs096M754HtP2IiHFcIQqwYNzHgKmjmfGdbk9JBkz/DNeDVsA5nc7qTnsSgULXTxwHSF286IJdco5kasaJm4Xurlm3V+2oiTugraBsi1J0Ht0OtHgJIlIaGxK7mY/QIDAQAB
----

Alternatively, we can instruct the MicroProfile JWT implementation to download the public key from a specific URL that returns a JSON Web Key Set (JWKS).

[source,properties]
----
#
# The public key of the authorization server (a.k.a. token creator)
#

mp.jwt.verify.publickey.location=https://tomitribe.okta.com/oauth2/v1/keys
----

## Testing a MicroProfile JWT Protected Endpoint

We will never have access to the production private key associated with the above public key, nor do we want to rely on external systems in our tests.  In a real-world project, you'll want to create mock JWTs that are very similar to the real JWTs you expect to get in production.

To accomplish this, we simply embed a test public/private keypair in our project (`testkey.pem`) and override the `microprofile-config.properties` file.

 - `src/test/java/org/superbiz/Tokens.java`
 - `src/test/resources/META-INF/microprofile-config.properties`
 - `src/test/resources/testkey.pem`

The important thing to note is the `src/test` version of the `microprofile-config.properties` has `config_ordinal=101` which gives those properties a higher order of precedence over the values in the `src/main/resources/META-INF/microprofile-config.properties` file which has the default `config_ordinal` of `100`.

[source,properties]
----
# Override the main META-INF/microprofile-config.properties
# It has an ordinal of 100, so the 101 below will always win
config_ordinal=101

#
# The public key associated with our testkey.pem
#
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlivFI8qB4D0y2jy0CfEqFyy46R0o7S8TKpsx5xbHKoU1VWg6QkQm+ntyIv1p4kE1sPEQO73+HY8+Bzs75XwRTYL1BmR1w8J5hmjVWjc6R2BTBGAYRPFRhor3kpM6ni2SPmNNhurEAHw7TaqszP5eUF/F9+KEBWkwVta+PZ37bwqSE4sCb1soZFrVz/UT/LF4tYpuVYt3YbqToZ3pZOZ9AX2o1GCG3xwOjkc4x0W7ezbQZdC9iftPxVHR8irOijJRRjcPDtA6vPKpzLl6CyYnsIYPd99ltwxTHjr3npfv/3Lw50bAkbT4HeLFxTx4flEoZLKO/g0bAoV2uqBhkA9xnQIDAQAB
----

From here, and with the help of a little `Tokens` utility class, we can send test requests at our server with mock JWTs as follows:

[source,java]
----
@Test
public void testAsManager() throws Exception {
    final WebClient webClient = createWebClient(base);

    final Movie movie = new Movie(1, "The Matrix", "Lana Wachowski");

    final String claims = "{" +
            "  \"sub\":\"Jane Awesome\"," +
            "  \"iss\":\"https://server.example.com\"," +
            "  \"groups\":[\"manager\",\"user\"]," +
            "  \"exp\":2552047942" +
            "}";

    final Response response = webClient.reset()
            .path("/api/movies")
            .header("Content-Type", "application/json")
            .header("Authorization", "Bearer " + Tokens.asToken(claims))
            .post(movie);
    assertEquals(204, response.getStatus());

}
----
